- name: add repo for java 8
  apt_repository: repo='ppa:webupd8team/java' state=present
  become: true

- name: set licence selected
  shell: /bin/echo debconf shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections
  become: yes

- name: set licence seen
  shell: /bin/echo debconf shared/accepted-oracle-license-v1-1 seen true | /usr/bin/debconf-set-selections
  become: yes

- name: install java 8
  apt: name=openjdk-8-jdk state=latest update-cache=yes force=yes
  become: yes

#- name: install wget
#  apt: name=wget state=present
#  tags: java8
#
#- name: create /usr/java directory
#  file: path=/usr/java state=directory owner=root group=root mode=0755
#  tags: java8
#
#- name: check jdk8 package downloaded
#  command: test -f {{ src_base_dir }}/jdk-{{ jdk8_pkg_version }}-linux-x64.tar.gz
#  register: jdk8_downloaded
#  failed_when: jdk8_downloaded.rc not in [0, 1]
#  changed_when: False
#  tags: java8
#
#- name: download jdk8 package
#  command: >
#    wget --no-cookies --no-check-certificate --header "Cookie: oraclelicense=accept-securebackup-cookie" "http://download.oracle.com/otn-pub/java/jdk/8u161-b12/2f38c3b165be4555a1fa6e98c45e0808/jdk-8u161-linux-x64.tar.gz" -O {{ src_base_dir }}/jdk-{{ jdk8_pkg_version }}-linux-x64.tar.gz
#  tags: java8
#
#
#- name: extract jdk8
#  command: >
#    tar -zxvf {{ src_base_dir }}/jdk-{{ jdk8_pkg_version }}-linux-x64.tar.gz
#    chdir=/usr/java
#    creates=/usr/java/jdk{{ jdk8_version }}
#  tags: java8
#
#- name: symlink to /usr/local
#  file: >
#    state=link
#    src=/usr/java/jdk{{ jdk8_version }}
#    dest=/usr/local/{{  symlink_to  }}
#    owner=root group=root
#  tags: java8
#
#- name: /etc/profile.d/java8.sh
#  template: >
#    src=profile.java8.sh.j2
#    dest=/etc/profile.d/{{  symlink_to  }}.sh
#    owner=root group=root mode=0644
#  tags: java8

